#!/usr/bin/env node
/**
 * Repo hygiene lint — what may and may not be committed.
 *
 * Separate from scripts/lint-design.mjs on purpose. The design-system lint is a
 * LINE scanner over source files and works fine on a single staged file; this one
 * asks questions of the git INDEX (`git ls-files`), which is a whole-repo
 * question. Two scanners in one script would mean neither could be run alone.
 *
 * Rules, each of which exists because it was already broken:
 *
 *  1. no-review-artefacts — no image or render output is tracked. Review frames
 *     are throwaway, they are megabytes, and `.gitignore`'s `*.png` cannot catch a
 *     file that was added with `git add -f`. This one can.
 *  2. no-review-dirs — no review/ render-out/ snapshots/ directory is committed.
 *     Frames belong outside the tree; `npm run review` writes them to the workspace
 *     .scratch directory for exactly that reason.
 *  3. no-loose-root-files — every file at the repo root is on an explicit allowlist.
 *     An allowlist fails LOUD when a new loose file appears, which is the point:
 *     `msg.txt`, `lint.json` and `build-report.json` all sat at the root and none of
 *     them belonged there. A denylist would have silently allowed the next one.
 *  4. no-secrets — no committed file may carry a private key, a Deepgram key, or a
 *     .env. Cheap, and the failure it prevents is not recoverable from git history.
 *
 * Run by lefthook on pre-commit and pre-push; available as `npm run lint:repo`.
 */

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/** Everything legal at the repo root. Anything else is a decision to make on purpose. */
const ROOT_ALLOWLIST = new Set([
  ".git", // a file, not a directory, inside a git worktree
  ".gitignore",
  "AGENTS.md", // agent instructions
  "CLAUDE.md",
  "DESIGN_SYSTEM.md", // binding design rules
  "README.md",
  "hyperframes.json", // HyperFrames project config
  "index.html", // GENERATED by scripts/entry.mjs — committed because every
  // root-level HyperFrames command reads it (see README, trap #2)
  "lefthook.yml",
  "meta.json", // project metadata
  "package.json",
  "package-lock.json",
]);

/** Directories a review frame or render artefact must never live in. */
const REVIEW_DIRS = ["snapshots", ".shots", "review", "out", "renders", "transcripts", ".scratch"];

/** Extensions that are review output or render output, never source. */
const ARTEFACT_EXT = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp",
  ".mp4", ".mov", ".mkv", ".avi", ".webm",
  ".mp3", ".wav", ".m4a", ".aac", ".ogg", ".flac",
  ".json.gz",
]);

/**
 * .svg is NOT in ARTEFACT_EXT, on purpose. The logo, the cursors and the Heroicons
 * are source assets and the compositions fail to render without them. `.svg` is
 * excluded, not forgotten.
 */

const failures = [];
const fail = (rule, msg) => failures.push(`  [${rule}] ${msg}`);

function git(...args) {
  return execFileSync("git", args, { cwd: ROOT, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
}

let tracked;
try {
  tracked = git("ls-files").split(/\r?\n/).filter(Boolean);
} catch {
  console.error("✗ repo lint: not a git repository (or git is unavailable) — nothing verified");
  process.exit(1);
}

// 1 + 2. Tracked artefacts and tracked review directories.
for (const f of tracked) {
  const ext = path.extname(f).toLowerCase();
  if (ARTEFACT_EXT.has(ext)) {
    fail(
      "no-review-artefacts",
      `${f} is a ${ext} and is TRACKED. Review frames and render output do not belong in this repo — ` +
        `run \`npm run review\` (it writes outside the tree) and delete this file. ` +
        `If it is genuinely source, it is not a ${ext}.`,
    );
  }
  const top = f.split("/")[0];
  if (REVIEW_DIRS.includes(top)) {
    fail(
      "no-review-dirs",
      `${top}/ is a review or render output directory and ${f} inside it is tracked. ` +
        `Delete it (\`git rm -r --cached ${top}\`) — .gitignore already excludes ${top}/.`,
    );
  }
}

// 3. Loose root files.
for (const f of fs.readdirSync(ROOT)) {
  if (fs.statSync(path.join(ROOT, f)).isDirectory()) continue;
  if (!ROOT_ALLOWLIST.has(f)) {
    fail(
      "no-loose-root-files",
      `${f} sits at the repo root and is not on the allowlist. Move it into src/ (build + design ` +
        `system modules), scripts/ (tooling), docs/ (documentation), narrations/ or assets/ — or add ` +
        `it to ROOT_ALLOWLIST in scripts/lint-repo.mjs if it genuinely belongs at the root.`,
    );
  }
}

// 4. Secrets.
const SECRET_PATTERNS = [
  { re: /-----BEGIN [A-Z ]*PRIVATE KEY-----/, what: "a private key" },
  { re: /dg_[a-z0-9]{20,}/i, what: "a Deepgram API key" },
  { re: /\bDEEPGRAM_API_KEY\s*=\s*\S/, what: "a hard-coded DEEPGRAM_API_KEY" },
];
const SCANNABLE = /\.(mjs|js|json|yml|yaml|md|ps1|html|css)$/i;
// Small cap: this is a pre-commit guard, not an audit of git history.
const SCAN_LIMIT = 512 * 1024;
let scanned = 0;
for (const f of tracked) {
  if (!SCANNABLE.test(f)) continue;
  const abs = path.join(ROOT, f);
  let st;
  try {
    st = fs.statSync(abs);
  } catch {
    continue;
  }
  if (!st.isFile() || st.size > SCAN_LIMIT) continue;
  scanned++;
  const text = fs.readFileSync(abs, "utf8");
  for (const { re, what } of SECRET_PATTERNS) {
    if (re.test(text)) fail("no-secrets", `${f} appears to contain ${what}`);
  }
}

if (failures.length) {
  console.error(`\n✗ repo lint failed — ${failures.length} problem${failures.length === 1 ? "" : "s"}\n`);
  console.error(failures.join("\n"));
  console.error(`\nRules: docs/WORKFLOW.md (repo hygiene)\n`);
  process.exit(1);
}

console.log(`✓ repo lint clean (4 rules, ${tracked.length} tracked files, ${scanned} scanned for secrets)`);